require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SocialMediaSitesController do

  # This should return the minimal set of attributes required to create a valid
  # SocialMediaSite. As you add validations to SocialMediaSite, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SocialMediaSitesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all social_media_sites as @social_media_sites" do
      social_media_site = SocialMediaSite.create! valid_attributes
      get :index, {}, valid_session
      assigns(:social_media_sites).should eq([social_media_site])
    end
  end

  describe "GET show" do
    it "assigns the requested social_media_site as @social_media_site" do
      social_media_site = SocialMediaSite.create! valid_attributes
      get :show, {:id => social_media_site.to_param}, valid_session
      assigns(:social_media_site).should eq(social_media_site)
    end
  end

  describe "GET new" do
    it "assigns a new social_media_site as @social_media_site" do
      get :new, {}, valid_session
      assigns(:social_media_site).should be_a_new(SocialMediaSite)
    end
  end

  describe "GET edit" do
    it "assigns the requested social_media_site as @social_media_site" do
      social_media_site = SocialMediaSite.create! valid_attributes
      get :edit, {:id => social_media_site.to_param}, valid_session
      assigns(:social_media_site).should eq(social_media_site)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SocialMediaSite" do
        expect {
          post :create, {:social_media_site => valid_attributes}, valid_session
        }.to change(SocialMediaSite, :count).by(1)
      end

      it "assigns a newly created social_media_site as @social_media_site" do
        post :create, {:social_media_site => valid_attributes}, valid_session
        assigns(:social_media_site).should be_a(SocialMediaSite)
        assigns(:social_media_site).should be_persisted
      end

      it "redirects to the created social_media_site" do
        post :create, {:social_media_site => valid_attributes}, valid_session
        response.should redirect_to(SocialMediaSite.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved social_media_site as @social_media_site" do
        # Trigger the behavior that occurs when invalid params are submitted
        SocialMediaSite.any_instance.stub(:save).and_return(false)
        post :create, {:social_media_site => { "name" => "invalid value" }}, valid_session
        assigns(:social_media_site).should be_a_new(SocialMediaSite)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SocialMediaSite.any_instance.stub(:save).and_return(false)
        post :create, {:social_media_site => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested social_media_site" do
        social_media_site = SocialMediaSite.create! valid_attributes
        # Assuming there are no other social_media_sites in the database, this
        # specifies that the SocialMediaSite created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SocialMediaSite.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => social_media_site.to_param, :social_media_site => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested social_media_site as @social_media_site" do
        social_media_site = SocialMediaSite.create! valid_attributes
        put :update, {:id => social_media_site.to_param, :social_media_site => valid_attributes}, valid_session
        assigns(:social_media_site).should eq(social_media_site)
      end

      it "redirects to the social_media_site" do
        social_media_site = SocialMediaSite.create! valid_attributes
        put :update, {:id => social_media_site.to_param, :social_media_site => valid_attributes}, valid_session
        response.should redirect_to(social_media_site)
      end
    end

    describe "with invalid params" do
      it "assigns the social_media_site as @social_media_site" do
        social_media_site = SocialMediaSite.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SocialMediaSite.any_instance.stub(:save).and_return(false)
        put :update, {:id => social_media_site.to_param, :social_media_site => { "name" => "invalid value" }}, valid_session
        assigns(:social_media_site).should eq(social_media_site)
      end

      it "re-renders the 'edit' template" do
        social_media_site = SocialMediaSite.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SocialMediaSite.any_instance.stub(:save).and_return(false)
        put :update, {:id => social_media_site.to_param, :social_media_site => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested social_media_site" do
      social_media_site = SocialMediaSite.create! valid_attributes
      expect {
        delete :destroy, {:id => social_media_site.to_param}, valid_session
      }.to change(SocialMediaSite, :count).by(-1)
    end

    it "redirects to the social_media_sites list" do
      social_media_site = SocialMediaSite.create! valid_attributes
      delete :destroy, {:id => social_media_site.to_param}, valid_session
      response.should redirect_to(social_media_sites_url)
    end
  end

end
